version: '3.8'

services:
  # Sales Service - Instancia 1
  sales-service-1:
    build:
      context: .
      dockerfile: Dockerfile.sales
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
    restart: unless-stopped

  # Sales Service - Instancia 2
  sales-service-2:
    build:
      context: .
      dockerfile: Dockerfile.sales
    ports:
      - "3011:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
    restart: unless-stopped

  # Accounting Service - Instancia 1
  accounting-service-1:
    build:
      context: .
      dockerfile: Dockerfile.accounting
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=production
    restart: unless-stopped

  # Accounting Service - Instancia 2
  accounting-service-2:
    build:
      context: .
      dockerfile: Dockerfile.accounting
    ports:
      - "3012:3002"
    environment:
      - PORT=3002
      - NODE_ENV=production
    restart: unless-stopped

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sales-service-1
      - sales-service-2
      - accounting-service-1
      - accounting-service-2
    restart: unless-stopped