FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY services/sales-service ./services/sales-service

EXPOSE 3001

CMD ["node", "services/sales-service/index.js"]