FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY services/accounting-service ./services/accounting-service

EXPOSE 3002

CMD ["node", "services/accounting-service/index.js"]